### ISSUE TITLE
gpEasy in root folder on cloud server

### ISSUE THREAD

**Issue by jozefkrz** [oyejorge/gpEasy-CMS#101]
Hi.

Trying to install gpEasy on my web server discovered following issue.
I've tried version 4.5 and 4.6RC and both are the same behavior.

I'm using virtual (cloud) web server form my hosting provider (home.pl).

When i'm install gpEasy in subdirectory, eg. www.main_domain.pl/my_page/ everything is ok. 
But when i'm install gpEasy in root directory of my server (www.main_domain.pl) - it's not ok.
Install process going right, but just after instalation i'm getting following error:

---
Notice: The site configuration did not load properly.
If you are the site administrator, you can troubleshoot the problem turning debugging "on" or bypass it by enabling gpEasy safe mode.
More information is available in the gpEasy documentation.

---

I have made some trace and investigation of root cause of this.
Discovered wrong paths and filenames in /data directory.

In my /data directory i have another directory named 'data' (/data/data/) which contains files with doubled .php extension in their names.
Below is result of ls:

/data/data
/data/data/index.html
/data/data/_site
/data/data/_site/index.html
/data/data/_site/pages.php.php
/data/data/_site/config.php.php
/data/data/_site/users.php.php
/data/data/_extra
/data/data/_extra/index.html
/data/data/_extra/Header.php.php
/data/data/_extra/Lorem.php.php
/data/data/_extra/Side_Menu.php.php
/data/data/_extra/Footer.php.php
/data/data/_extra/Contact.php.php

I've check that in my server when gpEasy is installed in root directory, then variable $dataDir is empty. 
Probably reason of this is filesystem available for user. Script which is available in browser at http://www.main_domain.pl/script.php is located in filesystem directly as '/script.php'  

Empty value of $dataDir couses multiple (2-times exactly) appending the '.php' extension in following functions:

files.php :: Get
files.php :: GetRaw
files.php :: Exists
files.php :: SaveData

In gpEasy 4.5 these functions was in common.php.

These functions has following part of code:

if( strpos($file,$dataDir) !== 0 ){
  $file = $dataDir.'/data/'.ltrim($file,'/').'.php';
}

When $dataDir is empty ( '/' is stripped to zero-length string), this code couses appending the '/data/' at the beginning of the file and '.php' at the end of the file, every time function is called.

I made additional contidion to make sure, that '.php' is added at the end of the file name only once.

if( strpos($file,$dataDir) !== 0 ){
  if (substr($file,-4)!==".php"){
    $file = $dataDir.'/data/'.ltrim($file,'/').'.php';
  }
}

After this modification (in 4 functions), cleaning /data directory and re-installing (go to install.php), gpEasy work fine.

Please consider my modification of these 4 functions. Maybe there is a better way to solve this?

Regards,
Krzysztof

**Comment by oyejorge** [comment]
Checking for '.php' at the end of the file instead of checking for $dataDir will actually be enough.
Thanks!
