### ISSUE TITLE
unable to add new content on any page that is chosen as first

### ISSUE THREAD

**Issue by borisp71** [oyejorge/gpEasy-CMS#32]
I install clean new web site, put few picture and when I try to add section, new blog post or else i receive message as attached.
Any Idea where is problem?
![1](https://f.cloud.github.com/assets/6475839/1979213/d022341c-83ae-11e3-9873-3623036e71b2.png)
![2](https://f.cloud.github.com/assets/6475839/1979214/d0247894-83ae-11e3-8f71-f7e1bf7f110d.png)

**Comment by oyejorge** [comment]
Closing old issues. Feel free to reopen if this is still a problem
