### ISSUE TITLE
JavaScript-Error occurs if a link is created

### ISSUE THREAD

**Issue by faultrier** [oyejorge/gpEasy-CMS#36]
Version: 4.3.4

Uncaught TypeError: undefined is not a function VM441:924
(anonymous function) VM441:924
j VM441:13
CKEDITOR.event.CKEDITOR.event.fire VM441:15
CKEDITOR.event.CKEDITOR.event.fireOnce VM441:15
(anonymous function) VM441:529
(anonymous function)

Reproduction:
1) edit content
2) select text
3) select "insert link" on the menu

**Comment by oyejorge** [comment]
Closing old issues. Feel free to reopen if this is still a problem
