### ISSUE TITLE
Toggle Panel Not Working

### ISSUE THREAD

**Issue by 2braincells2go** [oyejorge/gpEasy-CMS#40]
Hi. Nice job and thanks for sharing with community! Like to use gpEasy on school project.

Got it installed on local server (which is must, kids cannot access internet) without any errors, all passed during setup.

The panel that appears on start in top left will not close / collapse. When clicking the "left" arrow to collapse, the entire box highlights to move around screen.

Noe of the top buttons work in the panel such as collapse, home, setting or search? When attempting to click only option allowed is to move panel around on screen

Any ideas how to solve?

Many thanks in advance.

**Comment by dominionit** [comment]
Hi there, can you tell me what Browser and version you are using ? When you are logged in no yellow errors boxes appear at the top ,else if not, can you enable in your gpconfig.php file the option. define('gpdebug',true);
 and see if it then display errors ? Sounds like a Javascript issue, but would try and cover all possibilities, hope can be of help.

**Comment by 2braincells2go** [comment]
Hi and thank you for reply.

Using Chrome 40.0.2214.94m

In the developer console there are no errors including no javascript errors.

gpdebug to true and no errors.

Just tried in FF and console collapses as designed. Do not use other browsers very often as Chrome is fav. So error is related to Chrome.

Thanks!

**Comment by oyejorge** [comment]
Closing old issues. Feel free to reopen if this is still a problem
