### ISSUE TITLE
error 404 after upload to webhost

### ISSUE THREAD

**Issue by abda11ah** [oyejorge/gpEasy-CMS#41]
Hi,

I tried many web hosts and i always get an error 404 not found on after upload my GpEasy website.
It works fine on local Wampserver 2.5 x64 (Windows 7 x64) (Apache 2.4.9)

**Comment by dominionit** [comment]
For you whole site or parts of it ? Do you have a example site that gives this error that one can inspect ?

**Comment by abda11ah** [comment]
oops this was because i uploaded it to the root of the webhost.
On my local server GPeasy was stored under a folder called "gp", so the .htaccess file was not correctly synced.

**Comment by dominionit** [comment]
glad to hear you came right, have a good day.
