### ISSUE TITLE
Errors On Localhost

### ISSUE THREAD

**Issue by 2braincells2go** [oyejorge/gpEasy-CMS#42]
Hi and lovin' gpE! Great job.

I tried finding info on forum but when going to that link, nothing?

I generally develop on my local server and then migrate to online server. My issue is getting lot of errors. I figure most are missing modules and will work through that, but one issue has me stumped.

Using multiple site plugin and trying to setup:

Error Details

array(
   [type] => (integer)1
   [message] => (string)Call to undefined function ftp_connect()
   [file] => (string)/media/usb/http/testbed/gpeasy/include/tool/ftp.php
   [line] => (integer)17
   [request] => (string)/testbed/gpeasy/index.php/Admin_Site_Setup?cmd=settings
   [addon_name] => (string)Multiple Site
   [addon_id] => (string)16
   [time] => (integer)1423746333
   [request_method] => (string)GET
   [file_modified] => (integer)1422811205
   [file_size] => (integer)1829
)

Any ideas how to solve? Have changed permissions on ftp.php with no luck.

Many thanks in advance.

**Comment by oyejorge** [comment]
Just updated the plugin. Sorry for the late response
