### ISSUE TITLE
colorbox I8n -> Español

### ISSUE THREAD

**Issue by juek** [oyejorge/gpEasy-CMS#44]
/inlude/languages/es/main.inc:
line 487: 
'Image_of'=>'Imagen %1$ de %2$s',
should be: 
'Image_of'=>'Imagen %1$s de %2$s'
(insert 's' after %1$)

**Comment by barbrick** [comment]
@oyejorge This issue can be closed.

**Comment by oyejorge** [comment]
Thanks
