### ISSUE TITLE
Double login required?

### ISSUE THREAD

**Issue by M-Bab** [oyejorge/gpEasy-CMS#46]
Its nice to see the development continues again. gpEasy became my favorite CMS for simple webpages.

I have a reproducible bug with different browsers even applying on a completely fresh installed gpEasy 4.3 CMS: Whenever I want to login for site editing/administration I have to do this TWICE. There is no actual login after the first attempt. Only if this is followed up by an immediate second attempt the administration and editor tools become available.

Is this bug known/resolved in gpeasy 4.4?

**Comment by oyejorge** [comment]
I noticed that problem as well with 4.3 and yes, it is already fixed for 4.4!
