### ISSUE TITLE
Right-click brings up browser context menu

### ISSUE THREAD

**Issue by seidler2547** [oyejorge/gpEasy-CMS#52]
I'm using 4.5rc1/rc2 and I noticed that unlike in 4.4, right-clicking on an content area will bring up the browser context menu (in addition to the edit menu). It would be great if this could be restored to prevent the browser menu from appearing.

Using Firefox (Windows/Linux).

**Comment by oyejorge** [comment]
The new behaviour is actually intentional ([discussion on gpEasy.com](http://gpeasy.com/Forum?show=t1809)).

You can still disable the browser menu in your user preferences.
