### ISSUE TITLE
Unable to connect to backend

### ISSUE THREAD

**Issue by nvtv15** [oyejorge/gpEasy-CMS#53]
http://localhost/index.php/Admin_Uploaded
Unable to connect to backend
no uplaod on 4.4 gpeasy

:(

**Comment by barbrick** [comment]
@nvtv15 Working properly for me on version 4.4, this sounds like an environment specific issue and more information is required.

@oyejorge Could this issue be closed or marked invalid?

**Comment by oyejorge** [comment]
Seems appropriate since it's so old. Thanks
