### ISSUE TITLE
[Chrome] Warning: Cookies are required to continue

### ISSUE THREAD

**Issue by Fly06-Fr** [oyejorge/gpEasy-CMS#86]
Using a fresh install of the latest 4.6 Beta 3, I can't login in:

Warning: Cookies are required to continue. Refresh this page if you have cookies enabled.

Cookies are enabled and refreshing the page does not help.

Btw, This problem seems to be specific to Chrome, it does not happen on Firefox.

Chrome Version 45.0.2454.101 Ubuntu 14.04

**Comment by oyejorge** [comment]
I haven't had a chance to test it yet, but I'm guessing it has something to
do with the domain. By chance, is the domain for your test installation
http://localhost/ ?

**Comment by Fly06-Fr** [comment]
Good guess.

Please note that I did not experience such a problem with previous versions of gpEasy (including 4.6 Beta 2 as far as I can remember).

**Comment by oyejorge** [comment]
Confirmed bug and fix. Thanks!
