### ISSUE TITLE
autoprefixed $dataDir in theme -> $gp.LoadStyle

### ISSUE THREAD

**Issue by juek** [oyejorge/gpEasy-CMS#87]
When I use $gp.LoadStyle() in an editor component that's **part of a theme** (not plugin), it will auto-prefix the url with $dataDir, thus loading will fail. 
Maybe connected with [this commit](https://github.com/oyejorge/gpEasy-CMS/commit/2b1b32b64b9771df44f13ad37d97150cea1b182e)?
Example: **/gpeasyDir**/gepasyDir/themes/mytheme/assets/mysection_edit.css

**Comment by oyejorge** [comment]
I don't think LoadStyle() changed anytime recently. [The code does prepend the installation directory](https://github.com/oyejorge/gpEasy-CMS/blob/master/include/js/admin.js#L112-L120) which enables us to have things like this in the js: ```$gp.LoadStyle('/include/css/inline_edit.css');```

It's definitely not as straight forward with addons. Maybe we modify LoadStyle() like so:


```php
$gp.LoadStyle = function(file, already_prefixed){
	var d=new Date(),
		t=d.getTime();

	file = already_prefixed ? file : gpBase+file;

	//href set after appending to head so that it works properly in IE
	$('<link rel="stylesheet" type="text/css" />')
		.appendTo('head')
		.attr({'href':file+'?t='+t});
};
```

**Comment by juek** [comment]
> I don't think LoadStyle() changed anytime recently.

You're right. Sorry, seems I messed this up. I just used …

```php
$page->head_script .= "\nmyThemeBase = '" . dirname($page->theme_path) . "'; ";
```

but of course I need…

```php
$myThemeBase = strpos($addonRelativeCode,'/themes/') !== false ? '/themes/' . $addonFolderName : '/data/_themes/' . $addonFolderName;
$page->head_script .= "\nmyThemeBase = '" . $myThemeBase . "'; ";
```

```javascript
> $gp.LoadStyle = function(file, already_prefixed){...}
```

Yes, this would make it a little easier with addons for future gpEasy versions.
